pipeline {
    agent any
    stages {
        stage('Stage 1 Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Stage 2 Build Application Image'){
            steps {
                script {
                    dir('NodeApp') {
                        sh 'docker build -t akhilkumar119/node-app:latest .'
                    }
                }
            }
        }
        stage('Stage 3 Push to DockerHub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhubcreds', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
                        sh "echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin"
                        sh "docker push ${DOCKERHUB_USERNAME}/node-app:latest"
                    }
                }
            }
        }
    }
}